import React, { useState } from 'react';
import { StyleSheet, View, Text, ScrollView, Image, TouchableOpacity, Share } from 'react-native';
import Screen from '../components/Screen';
import { colors, spacing, radii } from '../theme/tokens';

// Was dead code before this migration (fetched a v8 Storage API off a v9 app
// object, which has no .storage() method). Now just renders the code string
// passed in via route.params - already generated locally in landing.js, or
// loaded from the server doc in sketchProfile.js when reopening a sketch.
// Toggles to the Enhance step's output when available.
export default function DisplaySourceCode({ route }) {
  const { sname, code, enhancedCode } = route.params;
  const [showEnhanced, setShowEnhanced] = useState(!!enhancedCode);
  const displayedCode = showEnhanced && enhancedCode ? enhancedCode : code;

  const shareEvent = () => {
    try {
      Share.share({
        message: displayedCode,
        title: `Layout: ${sname.replace(/_/g, ' ')} - code generated by auto layout`,
      });
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <Screen>
      {enhancedCode ? (
        <View style={styles.toggleRow}>
          <TouchableOpacity style={[styles.toggleButton, !showEnhanced && styles.toggleButtonActive]} onPress={() => setShowEnhanced(false)}>
            <Text style={[styles.toggleText, !showEnhanced && styles.toggleTextActive]}>Offline</Text>
          </TouchableOpacity>
          <TouchableOpacity style={[styles.toggleButton, showEnhanced && styles.toggleButtonActive]} onPress={() => setShowEnhanced(true)}>
            <Text style={[styles.toggleText, showEnhanced && styles.toggleTextActive]}>Enhanced ✨</Text>
          </TouchableOpacity>
        </View>
      ) : null}

      <ScrollView contentContainerStyle={styles.scrollViewContent}>
        <Text style={styles.code} selectable={true}>
          {displayedCode}
        </Text>
      </ScrollView>

      <TouchableOpacity
        activeOpacity={0.5}
        style={styles.fab}
        onPress={shareEvent}
      >
        <Image source={require('../assets/share.png')} style={styles.fabIcon} />
      </TouchableOpacity>
    </Screen>
  );
}

const styles = StyleSheet.create({
  toggleRow: {
    flexDirection: 'row',
    marginBottom: spacing.sm,
  },
  toggleButton: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radii.pill - 5,
    backgroundColor: colors.surface,
    marginHorizontal: spacing.xs,
  },
  toggleButtonActive: {
    backgroundColor: colors.primary,
  },
  toggleText: {
    color: colors.textPrimary,
    fontWeight: '500',
  },
  toggleTextActive: {
    color: colors.textOnPrimary,
  },
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: spacing.md,
  },
  code: {
    fontFamily: 'monospace',
    fontSize: 12,
    color: colors.textPrimary,
    textAlign: 'center',
    marginVertical: spacing.sm,
  },
  fab: {
    position: 'absolute',
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    right: spacing.md,
    bottom: spacing.md,
    backgroundColor: colors.primary,
    borderRadius: 64,
    shadowColor: 'rgba(0,0,0,.4)',
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: 1,
    shadowRadius: 1,
    elevation: 5,
  },
  fabIcon: {
    resizeMode: 'contain',
    width: 30,
    height: 30,
  },
});
